import {test,expect} from '@playwright/test';
test('couple settings, checklist, budget, guests and persistence',async({page})=>{
 await page.goto('/');
 await expect(page.getByRole('heading',{name:/설레는 시작/})).toBeVisible();
 await page.getByRole('button',{name:'결혼 날짜 정하기'}).click();
 await page.getByLabel('커플 이름').fill('Ethan & Love');
 await page.getByLabel('결혼 날짜').fill('2027-05-22');
 await page.getByLabel('총 예산 (원)').fill('20000000');
 await page.getByRole('button',{name:'저장하기'}).click();
 await page.getByRole('button',{name:'체크리스트',exact:true}).click();
 await page.getByRole('button',{name:'할 일 추가',exact:true}).click();
 await page.getByLabel('할 일',{exact:true}).fill('테스트 웨딩홀 예약');
 await page.getByLabel('준비 날짜 (선택)').fill('2027-01-20');
 await page.getByRole('button',{name:'저장하기'}).click();
 await page.getByRole('button',{name:'테스트 웨딩홀 예약 완료',exact:true}).click();
 await page.getByRole('button',{name:'완료',exact:true}).click();
 await expect(page.getByText('테스트 웨딩홀 예약',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'예산 관리',exact:true}).click();
 await page.getByRole('button',{name:'지출 추가'}).click();
 await page.getByLabel('지출 항목').fill('웨딩홀 계약금');
 await page.getByLabel('금액 (원)').fill('25000000');
 await page.getByRole('button',{name:'저장하기'}).click();
 await expect(page.getByText('예산 초과',{exact:true})).toBeVisible();
 await expect(page.getByRole('heading',{name:'5,000,000원',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'하객 관리',exact:true}).click();
 await page.getByRole('button',{name:'하객 추가'}).click();
 await page.getByLabel('이름',{exact:true}).fill('김친구');
 await page.getByRole('button',{name:'저장하기'}).click();
 await page.getByLabel('김친구 참석 여부').selectOption('참석');
 await page.reload();
 await page.getByRole('button',{name:'하객 관리',exact:true}).click();
 await expect(page.getByLabel('김친구 참석 여부')).toHaveValue('참석');
 await page.getByRole('button',{name:'우리의 일정',exact:true}).click();
 await expect(page.getByText('2027-01-20',{exact:true})).toBeVisible();
 await expect(page.getByText('2027-05-22',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'웨딩 영감',exact:true}).click();
 await page.getByRole('button',{name:'가든 웨딩 저장',exact:true}).click();
 await page.getByRole('button',{name:'저장한 영감'}).click();
 await expect(page.locator('.idea-card')).toHaveCount(1);
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'백업',exact:true}).click();
 expect((await downloadPromise).suggestedFilename()).toBe('our-chapter-backup.json');
 await page.getByRole('button',{name:'대시보드',exact:true}).click();
 await page.screenshot({path:'/tmp/our-chapter-desktop.png',fullPage:true,animations:'disabled'});
});
test('mobile navigation and layout',async({page})=>{
 await page.setViewportSize({width:390,height:844});
 await page.goto('/');
 await page.getByRole('button',{name:'메뉴 열기'}).click();
 await page.getByRole('button',{name:'체크리스트',exact:true}).click();
 await expect(page.getByRole('heading',{name:'체크리스트',exact:true})).toBeVisible();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
 await page.getByRole('button',{name:'할 일 추가',exact:true}).click();
 await expect(page.getByRole('dialog')).toBeVisible();
 await page.getByLabel('할 일',{exact:true}).fill('모바일 테스트');
 await page.getByRole('button',{name:'저장하기'}).click();
 await expect(page.getByText('모바일 테스트',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'메뉴 열기'}).click();
 await page.getByRole('button',{name:'대시보드',exact:true}).click();
 await page.screenshot({path:'/tmp/our-chapter-mobile.png',fullPage:true,animations:'disabled'});
});

test('backup restore validates records and deletion persists',async({page})=>{
 await page.goto('/');
 await page.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"couple":"broken"}')});
 await expect(page.getByRole('status')).toContainText('유효한');
 const data={couple:'Restored Couple',date:'2027-02-14',budget:1000,tasks:[],expenses:[{id:'e1',title:'복원 지출',category:'기타',amount:500}],guests:[],saved:[]};
 page.once('dialog',d=>d.accept());
 await page.locator('input[type=file]').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});
 await expect(page.getByRole('status')).toContainText('복원했습니다');
 await page.getByRole('button',{name:'예산 관리',exact:true}).click();
 await expect(page.getByText('복원 지출',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'복원 지출 삭제'}).click();
 await page.reload();
 await page.getByRole('button',{name:'예산 관리',exact:true}).click();
 await expect(page.getByText('복원 지출',{exact:true})).toHaveCount(0);
});

test('personalized heart branding and legacy data preservation',async({page})=>{
 await page.goto('/');
 await expect(page).toHaveTitle('송윤오 ♥ 박예은 · Our Chapter');
 await expect(page.locator('.hero-couple')).toHaveText('송윤오 ♥ 박예은');
 await expect(page.locator('.brand-icon')).toBeVisible();
 expect(await page.locator('.brand-icon').evaluate(img=>img.complete&&img.naturalWidth>0)).toBe(true);
 const favicon=page.locator('link[rel="icon"]');
 expect((await page.request.get(await favicon.getAttribute('href'))).status()).toBe(200);
 await page.screenshot({path:'/tmp/our-chapter-olive-desktop.png',fullPage:true,animations:'disabled'});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/our-chapter-olive-mobile.png',fullPage:true,animations:'disabled'});
 await page.evaluate(()=>localStorage.setItem('our-chapter-v1',JSON.stringify({couple:'Ethan & You',date:'2027-03-21',budget:12000000,tasks:[{id:'keep',title:'보존할 준비',category:'장소',due:'',done:true}],expenses:[{id:'expense',title:'보존할 지출',category:'기타',amount:10000}],guests:[{id:'guest',name:'친구',side:'함께',status:'참석'}],saved:['garden']})));
 await page.reload();
 await expect(page.locator('.hero-couple')).toHaveText('송윤오 ♥ 박예은');
 await expect(page.getByText('10,000원',{exact:true})).toBeVisible();
 await expect(page.getByText('1개 중 1개 완료',{exact:true})).toBeVisible();
 await expect(page.getByText('참석 확정 1명',{exact:true})).toBeVisible();
});
