import React,{useState,useRef,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard,CheckSquare,Wallet,Users,CalendarDays,Heart,ArrowUpRight,ArrowRight,Plus,Check,X,Settings,Download,Upload,Trash2,Menu,Flower2,Sparkles} from 'lucide-react';
import {initialData,daysUntil,totals,validBackup} from './model';
import './style.css';
const STORAGE='our-chapter-v1';
const nav=[['overview','대시보드',LayoutDashboard],['tasks','체크리스트',CheckSquare],['budget','예산 관리',Wallet],['guests','하객 관리',Users],['timeline','우리의 일정',CalendarDays],['inspiration','웨딩 영감',Heart]];
const money=n=>new Intl.NumberFormat('ko-KR').format(n);
const ideas=[{id:'garden',title:'A little garden romance',label:'가든 웨딩',tone:'garden',text:'햇살, 초록빛, 그리고 우리 둘. 자연스러운 야외 결혼식.'},{id:'table',title:'Gather around love',label:'테이블 스타일링',tone:'table',text:'따뜻한 촛불과 꽃 한 송이로 완성하는 작은 디테일.'},{id:'minimal',title:'Less, but meaningful',label:'미니멀 웨딩',tone:'minimal',text:'덜어낼수록 선명해지는 우리만의 이야기.'}];
function App(){
 const [data,setData]=useState(()=>{try {let d=JSON.parse(localStorage.getItem(STORAGE));return validBackup(d)?d:structuredClone(initialData)}catch{return structuredClone(initialData)}});
 const [page,setPage]=useState('overview'),[modal,setModal]=useState(null),[filter,setFilter]=useState('전체'),[mobile,setMobile]=useState(false),[notice,setNotice]=useState('');const importRef=useRef();
 const dialogRef=useRef(null),returnFocus=useRef(null);
 useEffect(()=>{if(!modal)return;returnFocus.current=document.activeElement;const dialog=dialogRef.current;const focusable=()=>[...dialog.querySelectorAll('button,input,select')].filter(el=>!el.disabled);focusable().find(el=>el.tagName==='INPUT')?.focus();function handle(e){if(e.key==='Escape'){setModal(null);return}if(e.key==='Tab'){const list=focusable(),first=list[0],last=list.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',handle);return()=>{document.removeEventListener('keydown',handle);returnFocus.current?.focus()}},[modal]);
 const stat=totals(data),days=daysUntil(data.date),progress=data.tasks.length?Math.round(stat.completed/data.tasks.length*100):0;
 function update(fn){setData(old=>{const next=fn(old);try{localStorage.setItem(STORAGE,JSON.stringify(next))}catch{setNotice('저장 공간을 사용할 수 없습니다. 데이터를 백업해 주세요.')}return next})}
 function go(p){setPage(p);setMobile(false);setFilter('전체')}
 function remove(type,id){update(d=>({...d,[type]:d[type].filter(t=>t.id!==id)}))}
 function submit(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));for(const key of ['title','name','couple']){if(key in f){f[key]=f[key].trim();if(!f[key]){setNotice('빈 이름이나 항목은 저장할 수 없습니다.');return}}}const id=crypto.randomUUID();if(modal==='settings')update(d=>({...d,couple:f.couple.trim(),date:f.date,budget:Number(f.budget)}));if(modal==='task')update(d=>({...d,tasks:[...d.tasks,{...f,id,done:false}]}));if(modal==='expense')update(d=>({...d,expenses:[...d.expenses,{...f,id,amount:Number(f.amount)}]}));if(modal==='guest')update(d=>({...d,guests:[...d.guests,{...f,id}]}));setModal(null)}
 function backup(){const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='our-chapter-backup.json';a.click();URL.revokeObjectURL(url);setNotice('백업 파일을 다운로드했습니다.')}
 async function restore(e){const file=e.target.files[0];if(!file)return;try{const next=JSON.parse(await file.text());if(!validBackup(next))throw Error();if(window.confirm('현재 기록을 백업 파일의 내용으로 교체할까요?')){update(()=>next);setNotice('백업을 복원했습니다.')}}catch{setNotice('유효한 Our Chapter 백업 파일이 아닙니다.')}e.target.value=''}
 function TaskList({limit}){let list=data.tasks.filter(t=>filter==='전체'||(filter==='완료'?t.done:!t.done));if(limit)list=list.filter(t=>!t.done).slice(0,3);return list.length?<div className="task-list">{list.map(t=><div className="task-row" key={t.id}><button className={'checkbox '+(t.done?'checked':'')} aria-label={`${t.title} ${t.done?'완료 취소':'완료'}`} onClick={()=>update(d=>({...d,tasks:d.tasks.map(x=>x.id===t.id?{...x,done:!x.done}:x)}))}>{t.done&&<Check size={13}/>}</button><div className={t.done?'done':''}><strong>{t.title}</strong><span>{t.due||'날짜 미정'}</span></div><small className="tag">{t.category}</small>{!limit&&<button className="icon-button" aria-label={`${t.title} 삭제`} onClick={()=>remove('tasks',t.id)}><Trash2 size={15}/></button>}</div>)}</div>:<div className="empty"><CheckSquare/> {limit?'지금 할 일을 모두 마쳤어요. 새로운 준비를 추가해 보세요.':'표시할 할 일이 없습니다.'}</div>}
 return <div className="app"><aside className={mobile?'sidebar open':'sidebar'}><a className="brand" href="#" onClick={e=>{e.preventDefault();go('overview')}}><Flower2 size={27}/><div>our chapter<span>WEDDING PLANNER</span></div></a><div className="sidebar-caption">OUR LITTLE BIG DAY</div><nav>{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>go(id)}><Icon size={19}/>{label}{id==='inspiration'&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="together"><Heart size={20}/><p>함께 준비하는<br/><b>우리의 가장 아름다운 날.</b></p><span>ONE STEP AT A TIME</span></div><button className="settings-link" onClick={()=>setModal('settings')}><Settings size={17}/> 웨딩 설정</button><span className="local-note">기록은 이 브라우저에 저장됩니다</span></div></aside>{mobile&&<button className="scrim" aria-label="메뉴 닫기" onClick={()=>setMobile(false)}/>}
 <div className="workspace"><header className="topbar"><div><button className="mobile-menu icon-button" aria-label="메뉴 열기" onClick={()=>setMobile(true)}><Menu/></button><span>우리의 결혼 준비</span><span className="crumb">/</span><b>{nav.find(n=>n[0]===page)[1]}</b></div><button className="couple" onClick={()=>setModal('settings')}><span className="avatar">E</span><span>{data.couple}</span><Settings size={15}/></button></header><main>
 {page==='overview'?<><div className="page-heading"><div><div className="eyebrow">LET’S WRITE OUR NEXT CHAPTER</div><h1>설레는 시작, 함께 준비해요 <Flower2 className="heading-flower" size={23}/></h1><p>작은 준비들이 모여, 우리만의 특별한 하루가 될 거예요.</p></div><button className="outline-button" onClick={()=>setModal('settings')}><CalendarDays size={16}/>{data.date?data.date.replaceAll('-','. '):'결혼 날짜 정하기'}</button></div>
 <section className="hero"><div className="hero-copy"><div className="eyebrow">OUR HAPPILY EVER AFTER</div><h2>A day to remember.<br/><i>A lifetime to love.</i></h2><p>우리다운 결혼식, 우리만의 속도로.<br/>가장 아름다운 다음 장을 함께 써 내려가요.</p><button onClick={()=>go('timeline')}>우리의 일정 보기 <ArrowRight size={17}/></button></div><div className="hero-art" aria-hidden="true"><div className="arch"><div className="sun"/><div className="vase"/><div className="stem s1"/><div className="stem s2"/><div className="stem s3"/><div className="bloom b1"/><div className="bloom b2"/><div className="bloom b3"/><div className="leaf l1"/><div className="leaf l2"/><div className="leaf l3"/></div><span className="art-note">a beautiful beginning</span></div><div className="countdown"><Heart size={15}/><span>TO OUR WEDDING</span><strong>{days===null?'D —':days>=0?`D − ${days}`:`D + ${Math.abs(days)}`}</strong><small>{data.date?`${data.date} · 우리의 날`:'우리의 날을 정해 주세요'}</small></div></section>
 <section className="stats"><Stat title="결혼 준비 진행률" icon={CheckSquare} value={`${progress}%`} sub={`${data.tasks.length}개 중 ${stat.completed}개 완료`}><div className="progress-track"><i style={{width:progress+'%'}}/></div></Stat><Stat title="우리의 웨딩 예산" icon={Wallet} value={`${money(stat.spent)}원`} sub={`총 예산 ${money(data.budget)}원`}><span className={stat.remaining<0?'over-budget':'stat-foot'}>{stat.remaining<0?'예산 초과':'남은 예산'} <b>{money(Math.abs(stat.remaining))}원</b></span></Stat><Stat title="함께할 소중한 사람들" icon={Users} value={`${data.guests.length}명`} sub={`참석 확정 ${stat.confirmed}명`}><span className="stat-foot">소중한 분들을 초대해 보세요 <Heart size={12}/></span></Stat></section>
 <div className="dashboard-grid"><section className="card"><div className="section-heading"><div><h3>지금 준비하면 좋은 일</h3><p>하나씩 체크할 때마다, 한 걸음 더 가까이.</p></div><button className="text-button" onClick={()=>go('tasks')}>전체 보기 <ArrowUpRight size={15}/></button></div><TaskList limit={3}/><button className="add-inline" onClick={()=>setModal('task')}><Plus size={16}/> 새로운 할 일 추가</button></section><section className="quote-card"><span className="eyebrow">A LITTLE REMINDER</span><Sparkles size={26}/><h3>완벽한 결혼식보다,<br/><i>우리다운 결혼식.</i></h3><p>가장 중요한 건,<br/>그날 함께 웃고 있을 우리니까요.</p><span className="quote-bottom">WITH LOVE, ALWAYS <Heart size={13}/></span></section></div>
 <section className="inspiration-section"><div className="section-heading"><div><h3>우리의 날을 위한 작은 영감</h3><p>마음에 드는 순간들을 모아 보세요.</p></div><button className="text-button" onClick={()=>go('inspiration')}>더 둘러보기 <ArrowUpRight size={15}/></button></div><IdeaCards/></section></>:<><div className="page-heading"><div><div className="eyebrow">OUR WEDDING, OUR WAY</div><h1>{nav.find(n=>n[0]===page)[1]}</h1><p>{{tasks:'작은 할 일부터 하나씩, 함께 완성해요.',budget:'소중한 하루를 위한 지출을 차근차근 기록해요.',guests:'우리의 시작을 함께할 사람들을 기억해요.',timeline:'함께 만들어 갈 순간들을 한눈에.',inspiration:'우리다운 결혼식을 위한 취향의 조각들.'}[page]}</p></div>{['tasks','budget','guests'].includes(page)&&<button className="primary-button" onClick={()=>setModal({tasks:'task',budget:'expense',guests:'guest'}[page])}><Plus size={17}/>{{tasks:'할 일 추가',budget:'지출 추가',guests:'하객 추가'}[page]}</button>}</div>
 {page==='tasks'&&<section className="card"><div className="filters">{['전체','진행 중','완료'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}<span>{stat.completed} / {data.tasks.length} 완료</span></div><TaskList/></section>}
 {page==='budget'&&<><section className="stats budget-stats"><Stat title="총 예산" icon={Wallet} value={money(data.budget)+'원'} sub="웨딩 설정에서 변경할 수 있어요"/><Stat title="기록한 지출" icon={CheckSquare} value={money(stat.spent)+'원'} sub={`${data.expenses.length}건의 지출`}/><Stat title={stat.remaining<0?'예산 초과':'남은 예산'} icon={Heart} value={money(Math.abs(stat.remaining))+'원'} sub={stat.remaining<0?'지출 계획을 다시 살펴보세요':'우리에게 중요한 곳에 사용해요'}/></section><section className="card"><h3>지출 내역</h3>{data.expenses.length?<div className="table-wrap"><table><thead><tr><th>항목</th><th>분류</th><th>금액</th><th><span className="sr-only">삭제</span></th></tr></thead><tbody>{data.expenses.map(e=><tr key={e.id}><td>{e.title}</td><td><span className="tag">{e.category}</span></td><td>{money(e.amount)}원</td><td><button className="icon-button" aria-label={`${e.title} 삭제`} onClick={()=>remove('expenses',e.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>:<Empty icon={Wallet} text="첫 지출을 기록하고 예산을 관리해 보세요."/>}</section></>}
 {page==='guests'&&<section className="card"><div className="section-heading"><h3>초대 목록 <span className="tag">{data.guests.length}명</span></h3><span>참석 {stat.confirmed} · 미정 {data.guests.filter(g=>g.status==='미정').length}</span></div>{data.guests.length?<div className="table-wrap"><table><thead><tr><th>이름</th><th>구분</th><th>참석 여부</th><th><span className="sr-only">삭제</span></th></tr></thead><tbody>{data.guests.map(g=><tr key={g.id}><td>{g.name}</td><td>{g.side}</td><td><select aria-label={`${g.name} 참석 여부`} value={g.status} onChange={e=>update(d=>({...d,guests:d.guests.map(x=>x.id===g.id?{...x,status:e.target.value}:x)}))}>{['미정','참석','불참'].map(s=><option key={s}>{s}</option>)}</select></td><td><button className="icon-button" aria-label={`${g.name} 삭제`} onClick={()=>remove('guests',g.id)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>:<Empty icon={Users} text="가장 먼저 초대하고 싶은 분은 누구인가요?"/>}</section>}
 {page==='timeline'&&<section className="card"><div className="section-heading"><h3>준비 일정</h3><button className="text-button" onClick={()=>setModal('task')}><Plus size={16}/> 일정 추가</button></div>{data.tasks.filter(t=>t.due).length?<div className="timeline">{data.tasks.filter(t=>t.due).sort((a,b)=>a.due.localeCompare(b.due)).map(t=><div className="timeline-item" key={t.id}><span className="timeline-dot"/><small>{t.due}</small><h3>{t.title}</h3><span className="tag">{t.done?'완료':t.category}</span></div>)}</div>:<Empty icon={CalendarDays} text="할 일에 날짜를 지정하면 여기에 일정이 표시돼요."/>}<div className="wedding-day"><Heart size={22}/><div><h3>우리의 결혼식</h3><p>{data.date||'아직 날짜를 정하지 않았어요.'}</p></div><button className="outline-button" onClick={()=>setModal('settings')}>날짜 설정</button></div></section>}
 {page==='inspiration'&&<><div className="filters">{['전체','저장한 영감'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div><IdeaCards/><p className="inspiration-note">스타일 제안용 일러스트입니다. 하트 버튼으로 마음에 드는 분위기를 저장하세요.</p></>}
 </>}
 <footer><span><Flower2 size={14}/> Made for your next chapter.</span><div><button onClick={backup}><Download size={14}/> 백업</button><button onClick={()=>importRef.current.click()}><Upload size={14}/> 복원</button><input type="file" accept="application/json,.json" hidden ref={importRef} onChange={restore}/></div></footer>
 </main></div>{notice&&<div className="toast" role="status">{notice}<button className="icon-button" aria-label="알림 닫기" onClick={()=>setNotice('')}><X size={16}/></button></div>}
 {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setModal(null)}} onKeyDown={e=>{if(e.key==='Escape')setModal(null)}}><section ref={dialogRef} className="modal" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div className="section-heading"><h2 id="modal-title">{{settings:'우리의 웨딩 설정',task:'새로운 할 일',expense:'지출 기록',guest:'소중한 하객 추가'}[modal]}</h2><button className="icon-button" aria-label="닫기" onClick={()=>setModal(null)}><X/></button></div><form onSubmit={submit}>
 {modal==='settings'?<><label>커플 이름<input autoFocus name="couple" required maxLength={60} defaultValue={data.couple}/></label><label>결혼 날짜<input type="date" name="date" defaultValue={data.date}/></label><label>총 예산 (원)<input type="number" name="budget" min="1" max="1000000000000" step="1" required defaultValue={data.budget}/></label><p className="form-note">데이터는 현재 브라우저에 저장됩니다. 다른 기기로 옮기려면 백업·복원을 사용하세요.</p></>:modal==='task'?<><label>할 일<input autoFocus name="title" placeholder="예: 웨딩홀 상담 예약하기" required maxLength={100}/></label><label>분류<select name="category">{['장소','예산','스튜디오','드레스','하객','여행','기타'].map(c=><option key={c}>{c}</option>)}</select></label><label>준비 날짜 (선택)<input name="due" type="date"/></label></>:modal==='expense'?<><label>지출 항목<input autoFocus name="title" required maxLength={100} placeholder="예: 웨딩홀 계약금"/></label><label>분류<select name="category">{['웨딩홀','스튜디오','드레스','메이크업','예물','여행','기타'].map(c=><option key={c}>{c}</option>)}</select></label><label>금액 (원)<input name="amount" type="number" required min="1" max="1000000000000" step="1" placeholder="0"/></label></>:<><label>이름<input autoFocus name="name" required maxLength={50} placeholder="하객 이름"/></label><label>구분<select name="side">{['함께','신랑 측','신부 측'].map(c=><option key={c}>{c}</option>)}</select></label><label>참석 여부<select name="status">{['미정','참석','불참'].map(c=><option key={c}>{c}</option>)}</select></label></>}
 <div className="modal-actions"><button type="button" className="outline-button" onClick={()=>setModal(null)}>취소</button><button className="primary-button" type="submit">저장하기 <Check size={16}/></button></div></form></section></div>}</div>;
 function IdeaCards(){const list=ideas.filter(i=>filter!=='저장한 영감'||data.saved.includes(i.id));return list.length?<div className="idea-grid">{list.map(i=><article className="idea-card" key={i.id}><div className={'idea-art '+i.tone}><div className="decor-circle"/><div className="decor-arch"/><div className="decor-flower"/><span className="art-caption">{i.label}</span><button className={'save-heart '+(data.saved.includes(i.id)?'saved':'')} aria-label={`${i.label} ${data.saved.includes(i.id)?'저장 취소':'저장'}`} onClick={()=>update(d=>({...d,saved:d.saved.includes(i.id)?d.saved.filter(s=>s!==i.id):[...d.saved,i.id]}))}><Heart size={17} fill={data.saved.includes(i.id)?'currentColor':'none'}/></button></div><div className="idea-copy"><span>{i.label}</span><h3>{i.title}</h3>{page==='inspiration'&&<p>{i.text}</p>}</div></article>)}</div>:<Empty icon={Heart} text="마음에 드는 영감의 하트를 눌러 저장해 보세요."/>}
}
function Stat({title,icon:Icon,value,sub,children}){return <article className="stat-card"><div className="stat-label">{title}<Icon size={17}/></div><h3>{value}</h3><p>{sub}</p>{children}</article>}
function Empty({icon:Icon,text}){return <div className="empty"><Icon size={30}/><p>{text}</p></div>}
createRoot(document.getElementById('root')).render(<App/>);
